/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasPrimarias;

import TelasSecundariasCompra.RealizarCompra;
import TelasSecundariasJogos.TelaPesquisaJogo;
import TelasSecundariasJogos.TelaTabelaJogo;
import TelasSecundariasJogos.TelaTabelaJogoVisaoCliente;
import codigo.Autenticar;
import codigo.Jogo;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yasmi_78vs0ei
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        jLClienteLogado.setText("Cliente: "+Autenticar.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPanel = new javax.swing.JDesktopPane();
        jLClienteLogado = new javax.swing.JLabel();
        jLDataAtual = new javax.swing.JLabel();
        jLHoraAtual = new javax.swing.JLabel();
        jLNomeEmpresa = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMTabelaJogos = new javax.swing.JMenuItem();
        mComprar = new javax.swing.JMenu();
        compraJogo = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jLClienteLogado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLClienteLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLClienteLogado.setText("Cliente: ");
        jLClienteLogado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLDataAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLDataAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDataAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLHoraAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLHoraAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLHoraAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLNomeEmpresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLNomeEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNomeEmpresa.setText("Nome empresa");
        jLNomeEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLClienteLogado, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLHoraAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLClienteLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLDataAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLHoraAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jMenu1.setText("Arquivo");
        jMenu1.setMaximumSize(new java.awt.Dimension(125, 32767));

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Jogos");
        jMenu2.setMaximumSize(new java.awt.Dimension(125, 32767));
        jMenu2.setMinimumSize(new java.awt.Dimension(61, 24));
        jMenu2.setPreferredSize(new java.awt.Dimension(61, 24));

        jMenuItem1.setText("Meus Jogos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setText("Procurar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMTabelaJogos.setText("Tabela de Jogos");
        jMTabelaJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTabelaJogosActionPerformed(evt);
            }
        });
        jMenu2.add(jMTabelaJogos);

        jMenuBar1.add(jMenu2);

        mComprar.setText("Comprar");
        mComprar.setMaximumSize(new java.awt.Dimension(125, 32767));
        mComprar.setPreferredSize(new java.awt.Dimension(61, 24));
        mComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mComprarActionPerformed(evt);
            }
        });

        compraJogo.setSelected(true);
        compraJogo.setText("Comprar Jogo");
        compraJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraJogoActionPerformed(evt);
            }
        });
        mComprar.add(compraJogo);

        jMenuBar1.add(mComprar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaPesquisaJogo telaPesquisaJogo = new TelaPesquisaJogo();
        telaPesquisaJogo.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mComprarActionPerformed
       
    }//GEN-LAST:event_mComprarActionPerformed

    private void compraJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraJogoActionPerformed
        RealizarCompra compra=new RealizarCompra();
        compra.setVisible(true);
    }//GEN-LAST:event_compraJogoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //abrir o sistema já maximizado
        this.setExtendedState(MAXIMIZED_BOTH);
               
        
        //data
       Date dataSistema=new Date();
       SimpleDateFormat formato= new SimpleDateFormat("dd/MM/yyyy");
       jLDataAtual.setText(formato.format(dataSistema)); 
       
       //hora
       Timer timer=new Timer(1000,new TelaCliente.hora());
       timer.start();
       
       //nome do usuário aparecendo na tela
       
    }//GEN-LAST:event_formWindowOpened

    private void jMTabelaJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTabelaJogosActionPerformed
       int aux = 0;
        
        String nome ="";
        String censura ="";
        String categoria ="";
        String desenvolvedora ="";
        String descricao ="";
        String quantidade ="";
        String preco="";
        
        ArrayList <Jogo> vetJogo = new ArrayList<>();
        try{
            FileInputStream fileinput = new FileInputStream("dadosJogo.txt");
            ObjectInputStream input = new ObjectInputStream(fileinput);
            //guarda o que foi lido no arrayList
            vetJogo = (ArrayList<Jogo>) input.readObject();
            TelaTabelaJogoVisaoCliente tabela = new TelaTabelaJogoVisaoCliente();
            DefaultTableModel envia = (DefaultTableModel) tabela.getTabelaJogo().getModel(); 
            
            //Jogo j = new Jogo(nome, censura, categoria, desenvolvedora, descricao, quantidade, preco);
            for(int i=0; i<vetJogo.size(); i++){
                Object [] jogo = {
                vetJogo.get(i).getNome(),
                vetJogo.get(i).getDesenvolvedora(),
                vetJogo.get(i).getCategoria(),
                vetJogo.get(i).getCensura(),
                vetJogo.get(i).getDescricao(),
                vetJogo.get(i).getPreco(),
                vetJogo.get(i).getTipo()};
                
                envia.addRow(jogo);
            }
            tabela.setVisible(true);
        }
        catch(IOException e1){
        }
        catch(ClassNotFoundException e2){
        }
    }//GEN-LAST:event_jMTabelaJogosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem compraJogo;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLClienteLogado;
    private javax.swing.JLabel jLDataAtual;
    private javax.swing.JLabel jLHoraAtual;
    private javax.swing.JLabel jLNomeEmpresa;
    private javax.swing.JMenuItem jMTabelaJogos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mComprar;
    // End of variables declaration//GEN-END:variables
class hora implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae) {
            Calendar now=Calendar.getInstance();
          jLHoraAtual.setText(String.format("%1$tH:%1$tM:%1$tS",now));
        }
  }
}
