/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasPrimarias;

import TelasSecundariasClientes.TelaCadastroCliente;
import TelasSecundariasClientes.TelaProcurarAtualizarRemoverCliente;
import TelasSecundariasCompra.RealizarCompra;
import TelasSecundariasEmpresas.ExcluirDadosEmpresa;
import TelasSecundariasEmpresas.PesquisaEmpresa;
import TelasSecundariasEmpresas.TelaAtualizarDadosEmpresa;
import TelasSecundariasEmpresas.TelaCaixadePesquisaEmpresa;
import TelasSecundariasFuncionarios.TelaCadastroValeCompras;
import TelasSecundariasFuncionarios.TelaConfirmarCompra;
import TelasSecundariasFuncionarios.TelaVisualizarValesCompras;
import TelasSecundariasJogos.TelaTabelaJogo;
import codigo.Autenticar;
import codigo.Jogo;
import codigo.ValidarValeCompras;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author yasmi_78vs0ei
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
        jButtonConfirmarCompra.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lampadaApagada.png")));
        jLFuncionarioLogado.setText("Funcionário: " + Autenticar.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanel = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLNomeEmpresa = new javax.swing.JLabel();
        jLFuncionarioLogado = new javax.swing.JLabel();
        jLDataAtual = new javax.swing.JLabel();
        jButtonConfirmarCompra = new javax.swing.JButton();
        jLHoraAtual = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArquivo_tFunc = new javax.swing.JMenu();
        jMSair_tFunc = new javax.swing.JMenuItem();
        jMClientes_tFunc = new javax.swing.JMenu();
        jMCadastroClientes_tFunc = new javax.swing.JMenuItem();
        jMConsultaCliente_tFunc = new javax.swing.JMenuItem();
        jMAtualizarCliente_tFunc = new javax.swing.JMenuItem();
        jMExcluirClientes_tFunc = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMConfirmarCompra_tFunc = new javax.swing.JMenuItem();
        jMDesenvolvedora_tFunc = new javax.swing.JMenu();
        jMConsultaDesenvolvedora_tFunc = new javax.swing.JMenuItem();
        jMAtualizarDesenvolvedora_tFunc = new javax.swing.JMenuItem();
        jMExcluirDesenvolvedora_tFunc = new javax.swing.JMenuItem();
        jMValeCompras = new javax.swing.JMenu();
        jMVisualizar = new javax.swing.JMenuItem();
        jMCadastrarValeCompras = new javax.swing.JMenuItem();
        jMExcluirValeCompras = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMTabelaJogos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema da Loja - Funcionário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jDesktopPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1065, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLNomeEmpresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLNomeEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNomeEmpresa.setText("Nome empresa");
        jLNomeEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLFuncionarioLogado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLFuncionarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFuncionarioLogado.setText("Funcionário: User");
        jLFuncionarioLogado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLDataAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLDataAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDataAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonConfirmarCompra.setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.Desktop.background"));
        jButtonConfirmarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lampada.png"))); // NOI18N
        jButtonConfirmarCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonConfirmarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarCompraActionPerformed(evt);
            }
        });

        jLHoraAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLHoraAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLHoraAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLNomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfirmarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLFuncionarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLHoraAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLDataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLHoraAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLFuncionarioLogado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonConfirmarCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
            .addComponent(jLNomeEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jMArquivo_tFunc.setText("Arquivo");
        jMArquivo_tFunc.setMaximumSize(new java.awt.Dimension(125, 32767));

        jMSair_tFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report_go.png"))); // NOI18N
        jMSair_tFunc.setText("Sair");
        jMSair_tFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSair_tFuncActionPerformed(evt);
            }
        });
        jMArquivo_tFunc.add(jMSair_tFunc);

        jMenuBar1.add(jMArquivo_tFunc);

        jMClientes_tFunc.setText("Clientes");
        jMClientes_tFunc.setMaximumSize(new java.awt.Dimension(125, 32767));

        jMCadastroClientes_tFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        jMCadastroClientes_tFunc.setText("Cadastrar Cliente");
        jMCadastroClientes_tFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastroClientes_tFuncActionPerformed(evt);
            }
        });
        jMClientes_tFunc.add(jMCadastroClientes_tFunc);

        jMConsultaCliente_tFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMConsultaCliente_tFunc.setText("Consultar");
        jMConsultaCliente_tFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsultaCliente_tFuncActionPerformed(evt);
            }
        });
        jMClientes_tFunc.add(jMConsultaCliente_tFunc);

        jMAtualizarCliente_tFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_edit.png"))); // NOI18N
        jMAtualizarCliente_tFunc.setText("Atualizar dados");
        jMAtualizarCliente_tFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAtualizarCliente_tFuncActionPerformed(evt);
            }
        });
        jMClientes_tFunc.add(jMAtualizarCliente_tFunc);

        jMExcluirClientes_tFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        jMExcluirClientes_tFunc.setText("Excluir dados");
        jMExcluirClientes_tFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMExcluirClientes_tFuncActionPerformed(evt);
            }
        });
        jMClientes_tFunc.add(jMExcluirClientes_tFunc);
        jMClientes_tFunc.add(jSeparator1);

        jMConfirmarCompra_tFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/package_go.png"))); // NOI18N
        jMConfirmarCompra_tFunc.setText("Confirmar compra");
        jMConfirmarCompra_tFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConfirmarCompra_tFuncActionPerformed(evt);
            }
        });
        jMClientes_tFunc.add(jMConfirmarCompra_tFunc);

        jMenuBar1.add(jMClientes_tFunc);

        jMDesenvolvedora_tFunc.setText("Desenvolvedora");
        jMDesenvolvedora_tFunc.setMaximumSize(new java.awt.Dimension(125, 32767));

        jMConsultaDesenvolvedora_tFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMConsultaDesenvolvedora_tFunc.setText("Consulta");
        jMConsultaDesenvolvedora_tFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsultaDesenvolvedora_tFuncActionPerformed(evt);
            }
        });
        jMDesenvolvedora_tFunc.add(jMConsultaDesenvolvedora_tFunc);

        jMAtualizarDesenvolvedora_tFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pencil_add.png"))); // NOI18N
        jMAtualizarDesenvolvedora_tFunc.setText("Atualizar dados");
        jMAtualizarDesenvolvedora_tFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAtualizarDesenvolvedora_tFuncActionPerformed(evt);
            }
        });
        jMDesenvolvedora_tFunc.add(jMAtualizarDesenvolvedora_tFunc);

        jMExcluirDesenvolvedora_tFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pencil_delete.png"))); // NOI18N
        jMExcluirDesenvolvedora_tFunc.setText("Excluir dados");
        jMExcluirDesenvolvedora_tFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMExcluirDesenvolvedora_tFuncActionPerformed(evt);
            }
        });
        jMDesenvolvedora_tFunc.add(jMExcluirDesenvolvedora_tFunc);

        jMenuBar1.add(jMDesenvolvedora_tFunc);

        jMValeCompras.setText("Vales-Compras");
        jMValeCompras.setPreferredSize(new java.awt.Dimension(115, 24));

        jMVisualizar.setText("Visualizar");
        jMVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarActionPerformed(evt);
            }
        });
        jMValeCompras.add(jMVisualizar);

        jMCadastrarValeCompras.setText("Cadastrar Vale-Compra");
        jMCadastrarValeCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarValeComprasActionPerformed(evt);
            }
        });
        jMValeCompras.add(jMCadastrarValeCompras);

        jMExcluirValeCompras.setText("Excluir");
        jMExcluirValeCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMExcluirValeComprasActionPerformed(evt);
            }
        });
        jMValeCompras.add(jMExcluirValeCompras);

        jMenuBar1.add(jMValeCompras);

        jMenu1.setText("Jogos");
        jMenu1.setPreferredSize(new java.awt.Dimension(115, 24));

        jMTabelaJogos.setText("Tabela de Jogos");
        jMTabelaJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTabelaJogosActionPerformed(evt);
            }
        });
        jMenu1.add(jMTabelaJogos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanel)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jMCadastroClientes_tFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastroClientes_tFuncActionPerformed
        //abrir tela de cadastro de cliente
        TelaCadastroCliente cadastro = new TelaCadastroCliente();
        cadastro.cadastrarCliente();
        cadastro.setVisible(true);


    }//GEN-LAST:event_jMCadastroClientes_tFuncActionPerformed

    private void jMSair_tFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSair_tFuncActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMSair_tFuncActionPerformed

    private void jMExcluirClientes_tFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMExcluirClientes_tFuncActionPerformed

        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF do Cliente que deseja atualizar: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraCliente = texto.getText();
        TelaProcurarAtualizarRemoverCliente tela = new TelaProcurarAtualizarRemoverCliente();
        tela.RemoverCliente(procuraCliente);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMExcluirClientes_tFuncActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //abrir o sistema já maximizado
        this.setExtendedState(MAXIMIZED_BOTH);

        //data
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jLDataAtual.setText(formato.format(dataSistema));

        //hora
        Timer timer = new Timer(1000, new hora());
        timer.start();

        Timer timer2 = new Timer(60000, new confirmaCompra());
        timer2.start();


    }//GEN-LAST:event_formWindowOpened

    private void jButtonConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarCompraActionPerformed
        TelaConfirmarCompra confirma = new TelaConfirmarCompra();
        confirma.setVisible(true);

    }//GEN-LAST:event_jButtonConfirmarCompraActionPerformed

    private void jMAtualizarCliente_tFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAtualizarCliente_tFuncActionPerformed

        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF do Cliente que deseja atualizar: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraCliente = texto.getText();
        TelaProcurarAtualizarRemoverCliente tela = new TelaProcurarAtualizarRemoverCliente();
        tela.AtualizarCliente(procuraCliente);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMAtualizarCliente_tFuncActionPerformed

    private void jMConsultaCliente_tFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultaCliente_tFuncActionPerformed

        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF do Cliente que deseja atualizar: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraCliente = texto.getText();
        TelaProcurarAtualizarRemoverCliente tela = new TelaProcurarAtualizarRemoverCliente();
        tela.PesquisarCliente(procuraCliente);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMConsultaCliente_tFuncActionPerformed

    private void jMConsultaDesenvolvedora_tFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultaDesenvolvedora_tFuncActionPerformed
        TelaCaixadePesquisaEmpresa pesquisa = new TelaCaixadePesquisaEmpresa();
        pesquisa.setVisible(true);
    }//GEN-LAST:event_jMConsultaDesenvolvedora_tFuncActionPerformed

    private void jMAtualizarDesenvolvedora_tFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAtualizarDesenvolvedora_tFuncActionPerformed
        TelaAtualizarDadosEmpresa att = new TelaAtualizarDadosEmpresa();
        att.setVisible(true);
    }//GEN-LAST:event_jMAtualizarDesenvolvedora_tFuncActionPerformed

    private void jMExcluirDesenvolvedora_tFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMExcluirDesenvolvedora_tFuncActionPerformed
        ExcluirDadosEmpresa exclui = new ExcluirDadosEmpresa();
        exclui.setVisible(true);
    }//GEN-LAST:event_jMExcluirDesenvolvedora_tFuncActionPerformed

    private void jMConfirmarCompra_tFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConfirmarCompra_tFuncActionPerformed
        TelaConfirmarCompra confirmaCompra = new TelaConfirmarCompra();
        confirmaCompra.setVisible(true);
    }//GEN-LAST:event_jMConfirmarCompra_tFuncActionPerformed

    private void jMCadastrarValeComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarValeComprasActionPerformed
        TelaCadastroValeCompras cadastroVale = new TelaCadastroValeCompras();
        cadastroVale.setVisible(true);
    }//GEN-LAST:event_jMCadastrarValeComprasActionPerformed

    private void jMExcluirValeComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMExcluirValeComprasActionPerformed
        //pedir cliente para digitar cartão de crédito
        JTextField entrada = new JTextField("");

        JLabel label = new JLabel("Informe a identificacao do vale-compras que deseja excluir:");
        JOptionPane.showMessageDialog(null, new Object[]{label, entrada});
        String procura = entrada.getText();
        ValidarValeCompras excluiVale = new ValidarValeCompras();
        if (!procura.equals("")) {
            try {
                excluiVale.removerValeCompras(procura);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Identificação inválida!");
            }
        }
    }//GEN-LAST:event_jMExcluirValeComprasActionPerformed

    private void jMVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarActionPerformed
        TelaVisualizarValesCompras visualizaVales = new TelaVisualizarValesCompras();
        visualizaVales.setVisible(true);
    }//GEN-LAST:event_jMVisualizarActionPerformed

    private void jMTabelaJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTabelaJogosActionPerformed
        int aux = 0;
        
        String nome ="";
        String censura ="";
        String categoria ="";
        String desenvolvedora ="";
        String descricao ="";
        String quantidade ="";
        String preco="";
        
        ArrayList <Jogo> vetJogo = new ArrayList<>();
        try{
            FileInputStream fileinput = new FileInputStream("dadosJogo.txt");
            ObjectInputStream input = new ObjectInputStream(fileinput);
            //guarda o que foi lido no arrayList
            vetJogo = (ArrayList<Jogo>) input.readObject();
            TelaTabelaJogo tabela = new TelaTabelaJogo();
            DefaultTableModel envia = (DefaultTableModel) tabela.getTabelaJogo().getModel(); 
            
            //Jogo j = new Jogo(nome, censura, categoria, desenvolvedora, descricao, quantidade, preco);
            for(int i=0; i<vetJogo.size(); i++){
                Object [] jogo = {
                vetJogo.get(i).getNome(),
                vetJogo.get(i).getDesenvolvedora(),
                vetJogo.get(i).getCategoria(),
                vetJogo.get(i).getCensura(),
                vetJogo.get(i).getDescricao(),
                vetJogo.get(i).getQuantidade(),
                vetJogo.get(i).getPreco(),
                vetJogo.get(i).getTipo()};
                
                envia.addRow(jogo);
            }
            tabela.setVisible(true);
        }
        catch(IOException e1){
        }
        catch(ClassNotFoundException e2){
        }
    }//GEN-LAST:event_jMTabelaJogosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConfirmarCompra;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLDataAtual;
    private javax.swing.JLabel jLFuncionarioLogado;
    private javax.swing.JLabel jLHoraAtual;
    private javax.swing.JLabel jLNomeEmpresa;
    private javax.swing.JMenu jMArquivo_tFunc;
    private javax.swing.JMenuItem jMAtualizarCliente_tFunc;
    private javax.swing.JMenuItem jMAtualizarDesenvolvedora_tFunc;
    private javax.swing.JMenuItem jMCadastrarValeCompras;
    private javax.swing.JMenuItem jMCadastroClientes_tFunc;
    private javax.swing.JMenu jMClientes_tFunc;
    private javax.swing.JMenuItem jMConfirmarCompra_tFunc;
    private javax.swing.JMenuItem jMConsultaCliente_tFunc;
    private javax.swing.JMenuItem jMConsultaDesenvolvedora_tFunc;
    private javax.swing.JMenu jMDesenvolvedora_tFunc;
    private javax.swing.JMenuItem jMExcluirClientes_tFunc;
    private javax.swing.JMenuItem jMExcluirDesenvolvedora_tFunc;
    private javax.swing.JMenuItem jMExcluirValeCompras;
    private javax.swing.JMenuItem jMSair_tFunc;
    private javax.swing.JMenuItem jMTabelaJogos;
    private javax.swing.JMenu jMValeCompras;
    private javax.swing.JMenuItem jMVisualizar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
 class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            Calendar now = Calendar.getInstance();
            jLHoraAtual.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }

    class confirmaCompra implements ActionListener {

        public void actionPerformed(ActionEvent ae) {
            //lampada ficara acesa qdo tabela estiver com compras para confirmar
            if (TelaConfirmarCompra.isTabelaComPendencias()) {
                jButtonConfirmarCompra.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lampada.png")));
            }
        }
    }
}
