/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasPrimarias;

import TelasSecundariasRelatorio.gerarRelatorio;
import TelasSecundariasEmpresas.PesquisaEmpresa;
import TelasSecundariasAdministrador.TelaAdicionarAdm;
import TelasSecundariasAdministrador.TelaExcluirAdm;
import TelasSecundariasAdministrador.TelaProcurarAtualizarAdm;
import TelasSecundariasClientes.TelaCadastroCliente;
import TelasSecundariasClientes.TelaProcurarAtualizarRemoverCliente;
import TelasSecundariasCompra.RealizarCompra;
import TelasSecundariasEmpresas.ExcluirDadosEmpresa;
import TelasSecundariasEmpresas.TelaAtualizarDadosEmpresa;
import TelasSecundariasEmpresas.TelaCadastroEmpresa;
import TelasSecundariasEmpresas.TelaCaixadePesquisaEmpresa;
import TelasSecundariasFuncionarios.TelaAlternativaPesquisa;
import TelasSecundariasFuncionarios.TelaCadastroFuncionario;
import TelasSecundariasFuncionarios.TelaExcluirFuncionario;
import TelasSecundariasFuncionarios.TelaProcurarAtualizarFuncionario;
import TelasSecundariasJogos.TelaAlternativaP;
import TelasSecundariasJogos.TelaAtualizaJogo;
import TelasSecundariasJogos.TelaCadastroJogo;
import TelasSecundariasJogos.TelaExcluirJogo;
import TelasSecundariasJogos.TelaPesquisaJogo;
import TelasSecundariasJogos.TelaTabelaJogo;
import codigo.Autenticar;
import codigo.Jogo;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author yasmi_78vs0ei
 */
public class TelaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministrador
     */
    public TelaAdministrador() {
        initComponents();
        jLAdmLogado.setText("Administrador: "+Autenticar.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLNomeEmpresa = new javax.swing.JLabel();
        jLAdmLogado = new javax.swing.JLabel();
        jLDataAtual = new javax.swing.JLabel();
        jLHoraAtual = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArquivo_tFunc = new javax.swing.JMenu();
        jMenuAbrirRelatorio = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenuItem();
        jMArquivo_tFunc1 = new javax.swing.JMenu();
        jMenuAdicionarFuncionario = new javax.swing.JMenuItem();
        jAtualizarFunc = new javax.swing.JMenuItem();
        jMenuProcurarFuncionario = new javax.swing.JMenuItem();
        jMenuExcluirFuncionario = new javax.swing.JMenuItem();
        jPesquisaPersonalizada = new javax.swing.JMenuItem();
        jMArquivo_tFunc2 = new javax.swing.JMenu();
        jMenuAdicionarCliente = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuProcurarCliene = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMArquivo_tFunc3 = new javax.swing.JMenu();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMTabelaJogos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMArquivo_tFunc5 = new javax.swing.JMenu();
        jMenuaddAds = new javax.swing.JMenuItem();
        jMenuItemProcurarAdm = new javax.swing.JMenuItem();
        jMenuAttAdm = new javax.swing.JMenuItem();
        jMenuexcluirAdmin = new javax.swing.JMenuItem();
        jMArquivo_tFunc4 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema da Loja - Administrador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLNomeEmpresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLNomeEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNomeEmpresa.setText("Nome empresa");
        jLNomeEmpresa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLAdmLogado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLAdmLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAdmLogado.setText("Administrador: ");
        jLAdmLogado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLDataAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLDataAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDataAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLHoraAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLHoraAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLHoraAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jDesktopPane1.setDoubleBuffered(true);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jMenuBar1.setRequestFocusEnabled(false);

        jMArquivo_tFunc.setText("Arquivo");
        jMArquivo_tFunc.setMaximumSize(new java.awt.Dimension(125, 32767));

        jMenuAbrirRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report.png"))); // NOI18N
        jMenuAbrirRelatorio.setText("Abrir Relatorio");
        jMenuAbrirRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAbrirRelatorioMouseClicked(evt);
            }
        });
        jMenuAbrirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirRelatorioActionPerformed(evt);
            }
        });
        jMArquivo_tFunc.add(jMenuAbrirRelatorio);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report_go.png"))); // NOI18N
        jMenuSair.setText("Sair do Sistema");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMArquivo_tFunc.add(jMenuSair);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/drive_user.png"))); // NOI18N
        jMenuSobre.setText("Atualizações/Equipe");
        jMArquivo_tFunc.add(jMenuSobre);

        jMenuBar1.add(jMArquivo_tFunc);

        jMArquivo_tFunc1.setText("Funcionários");
        jMArquivo_tFunc1.setMaximumSize(new java.awt.Dimension(125, 32767));

        jMenuAdicionarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        jMenuAdicionarFuncionario.setText("Adicionar Funcionário");
        jMenuAdicionarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdicionarFuncionarioActionPerformed(evt);
            }
        });
        jMArquivo_tFunc1.add(jMenuAdicionarFuncionario);

        jAtualizarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_edit.png"))); // NOI18N
        jAtualizarFunc.setText("Atualizar Funcionário");
        jAtualizarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtualizarFuncActionPerformed(evt);
            }
        });
        jMArquivo_tFunc1.add(jAtualizarFunc);

        jMenuProcurarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuProcurarFuncionario.setText("Procurar Funcionário");
        jMenuProcurarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProcurarFuncionarioActionPerformed(evt);
            }
        });
        jMArquivo_tFunc1.add(jMenuProcurarFuncionario);

        jMenuExcluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        jMenuExcluirFuncionario.setText("Excluir Funcionário");
        jMenuExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExcluirFuncionarioActionPerformed(evt);
            }
        });
        jMArquivo_tFunc1.add(jMenuExcluirFuncionario);

        jPesquisaPersonalizada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jPesquisaPersonalizada.setText("Pesquisa por nome ou CPF");
        jPesquisaPersonalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisaPersonalizadaActionPerformed(evt);
            }
        });
        jMArquivo_tFunc1.add(jPesquisaPersonalizada);

        jMenuBar1.add(jMArquivo_tFunc1);

        jMArquivo_tFunc2.setText("Clientes");
        jMArquivo_tFunc2.setMaximumSize(new java.awt.Dimension(125, 32767));

        jMenuAdicionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        jMenuAdicionarCliente.setText("Adicionar");
        jMenuAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdicionarClienteActionPerformed(evt);
            }
        });
        jMArquivo_tFunc2.add(jMenuAdicionarCliente);

        jMenuItem28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_edit.png"))); // NOI18N
        jMenuItem28.setText("Atualizar");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc2.add(jMenuItem28);

        jMenuProcurarCliene.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuProcurarCliene.setText("Procurar");
        jMenuProcurarCliene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProcurarClieneActionPerformed(evt);
            }
        });
        jMArquivo_tFunc2.add(jMenuProcurarCliene);

        jMenuItem30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        jMenuItem30.setText("Excluir");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc2.add(jMenuItem30);

        jMenuBar1.add(jMArquivo_tFunc2);

        jMArquivo_tFunc3.setText("Jogos");
        jMArquivo_tFunc3.setMaximumSize(new java.awt.Dimension(125, 32767));

        jMenuItem39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report_add.png"))); // NOI18N
        jMenuItem39.setText("Adicionar");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc3.add(jMenuItem39);

        jMenuItem40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report_edit.png"))); // NOI18N
        jMenuItem40.setText("Atualizar");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc3.add(jMenuItem40);

        jMenuItem41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report_disk.png"))); // NOI18N
        jMenuItem41.setText("Procurar");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc3.add(jMenuItem41);

        jMenuItem42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report_delete.png"))); // NOI18N
        jMenuItem42.setText("Excluir");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc3.add(jMenuItem42);

        jMTabelaJogos.setText("Tabela de Jogos");
        jMTabelaJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTabelaJogosActionPerformed(evt);
            }
        });
        jMArquivo_tFunc3.add(jMTabelaJogos);

        jMenuItem1.setText("Pesquisa Alternativa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc3.add(jMenuItem1);

        jMenuBar1.add(jMArquivo_tFunc3);

        jMArquivo_tFunc5.setText("Administradores");
        jMArquivo_tFunc5.setMaximumSize(new java.awt.Dimension(125, 32767));

        jMenuaddAds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-adicionar-grupo-de-usuários-mulher-homem-20.png"))); // NOI18N
        jMenuaddAds.setText("Adicionar Administrador");
        jMenuaddAds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuaddAdsActionPerformed(evt);
            }
        });
        jMArquivo_tFunc5.add(jMenuaddAds);

        jMenuItemProcurarAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        jMenuItemProcurarAdm.setText("Procurar Administrador");
        jMenuItemProcurarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProcurarAdmActionPerformed(evt);
            }
        });
        jMArquivo_tFunc5.add(jMenuItemProcurarAdm);

        jMenuAttAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-alterar-usuário-feminino-20.png"))); // NOI18N
        jMenuAttAdm.setText("Atualizar Administador");
        jMenuAttAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAttAdmActionPerformed(evt);
            }
        });
        jMArquivo_tFunc5.add(jMenuAttAdm);

        jMenuexcluirAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-apagar-para-sempre-20.png"))); // NOI18N
        jMenuexcluirAdmin.setText("Excluir Administrador");
        jMenuexcluirAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuexcluirAdminActionPerformed(evt);
            }
        });
        jMArquivo_tFunc5.add(jMenuexcluirAdmin);

        jMenuBar1.add(jMArquivo_tFunc5);

        jMArquivo_tFunc4.setText("Empresas");
        jMArquivo_tFunc4.setMaximumSize(new java.awt.Dimension(125, 32767));

        jMenuItem31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report_add.png"))); // NOI18N
        jMenuItem31.setText("Adicionar");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc4.add(jMenuItem31);

        jMenuItem32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report_edit.png"))); // NOI18N
        jMenuItem32.setText("Atualizar");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc4.add(jMenuItem32);

        jMenuItem33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report_disk.png"))); // NOI18N
        jMenuItem33.setText("Procurar");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc4.add(jMenuItem33);

        jMenuItem34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/report_delete.png"))); // NOI18N
        jMenuItem34.setText("Excluir");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMArquivo_tFunc4.add(jMenuItem34);

        jMenuBar1.add(jMArquivo_tFunc4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAdmLogado, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLHoraAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLAdmLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLDataAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLHoraAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jDesktopPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @param evt função quando a tela é aberta
 */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(MAXIMIZED_BOTH);

        //data
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jLDataAtual.setText(formato.format(dataSistema));

        //hora
        Timer timer2 = new Timer(1000, new TelaAdministrador.hora());
        timer2.start();
        Login l = new Login();
        String u = l.getjTextFieldLogin().getText();
        jLAdmLogado.setText(u);

        //nome do usuário aparecendo na tela
    }//GEN-LAST:event_formWindowOpened

    private void jMenuAbrirRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAbrirRelatorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAbrirRelatorioMouseClicked

    private void jMenuAbrirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirRelatorioActionPerformed
           gerarRelatorio relatorio = new gerarRelatorio();
           relatorio.setVisible(true);
    }//GEN-LAST:event_jMenuAbrirRelatorioActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuAdicionarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdicionarFuncionarioActionPerformed

        TelaCadastroFuncionario cadastro = new TelaCadastroFuncionario();
        cadastro.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAdicionarFuncionarioActionPerformed

    private void jMenuProcurarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProcurarFuncionarioActionPerformed
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF que deseja procurar: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraFunc = texto.getText();
        TelaProcurarAtualizarFuncionario tela = new TelaProcurarAtualizarFuncionario(procuraFunc);
        tela.pesquisa(procuraFunc);

    }//GEN-LAST:event_jMenuProcurarFuncionarioActionPerformed

    private void jMenuExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExcluirFuncionarioActionPerformed
        // TODO add your handling code here:
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF do Funcionário que deseja excluir: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraFunc = texto.getText();
        TelaExcluirFuncionario tela = new TelaExcluirFuncionario(procuraFunc);
        tela.Pesquisa(procuraFunc);

    }//GEN-LAST:event_jMenuExcluirFuncionarioActionPerformed
    /**
     * Adicionar um novo administrador.
     */
    private void jMenuaddAdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuaddAdsActionPerformed
        // TODO add your handling code here:
        TelaAdicionarAdm adicionar = new TelaAdicionarAdm();
        adicionar.setVisible(true);
    }//GEN-LAST:event_jMenuaddAdsActionPerformed
    /**
     * Procurar por um adminnistrador.
     */
    private void jMenuItemProcurarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProcurarAdmActionPerformed
        //Uso de uma mascara na caixa de pesquisa por CPF para melhor interação com usuário
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF que deseja procurar: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraAdmin = texto.getText();
        TelaProcurarAtualizarAdm tela = new TelaProcurarAtualizarAdm(procuraAdmin);
        tela.pesquisa(procuraAdmin);


    }//GEN-LAST:event_jMenuItemProcurarAdmActionPerformed

    private void jMenuAttAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAttAdmActionPerformed
        // TODO add your handling code here:
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF do Administrador que deseja atualizar: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraAdmin = texto.getText();
        TelaProcurarAtualizarAdm tela = new TelaProcurarAtualizarAdm(procuraAdmin);
        tela.Atualizar();

    }//GEN-LAST:event_jMenuAttAdmActionPerformed

    private void jMenuexcluirAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuexcluirAdminActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF do Administrador que deseja excluir: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraAdmin = texto.getText();
        TelaExcluirAdm tela = new TelaExcluirAdm(procuraAdmin);
        tela.pesquisa(procuraAdmin);
    }//GEN-LAST:event_jMenuexcluirAdminActionPerformed

    private void jAtualizarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtualizarFuncActionPerformed
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF do Funcionario que deseja atualizar: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraFunc = texto.getText();
        TelaProcurarAtualizarFuncionario tela = new TelaProcurarAtualizarFuncionario(procuraFunc);
        tela.atualizar();

        // TODO add your handling code here:
    }//GEN-LAST:event_jAtualizarFuncActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF do Cliente: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraCliente = texto.getText();
        TelaProcurarAtualizarRemoverCliente telapar = new TelaProcurarAtualizarRemoverCliente();
        telapar.AtualizarCliente(procuraCliente);
        
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdicionarClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroCliente telaCF = new TelaCadastroCliente();
        telaCF.setVisible(true);
    }//GEN-LAST:event_jMenuAdicionarClienteActionPerformed

    private void jMenuProcurarClieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProcurarClieneActionPerformed
        // TODO add your handling code here:
         MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF do Cliente: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraCliente = texto.getText();
        TelaProcurarAtualizarRemoverCliente telapar = new TelaProcurarAtualizarRemoverCliente();
        telapar.PesquisarCliente(procuraCliente);
    }//GEN-LAST:event_jMenuProcurarClieneActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
        TelaProcurarAtualizarRemoverCliente telaparc = new TelaProcurarAtualizarRemoverCliente();
        MaskFormatter formato = null;
          try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF do Cliente que deseja excluir: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String procuraCliente = texto.getText();
        TelaProcurarAtualizarRemoverCliente telapar = new TelaProcurarAtualizarRemoverCliente();
        telapar.RemoverCliente(procuraCliente);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        TelaCadastroJogo telaCadastroJogo = new TelaCadastroJogo();
        telaCadastroJogo.setVisible(true);
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        TelaExcluirJogo telaExcluirJogo = new TelaExcluirJogo();
        telaExcluirJogo.setVisible(true);
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        TelaPesquisaJogo telaPesquisaJogo = new TelaPesquisaJogo();
        telaPesquisaJogo.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        TelaAtualizaJogo telaAtualizaJogo = new TelaAtualizaJogo();
        telaAtualizaJogo.setVisible(true);
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMTabelaJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTabelaJogosActionPerformed
        
        int aux = 0;
        
        String nome ="";
        String censura ="";
        String categoria ="";
        String desenvolvedora ="";
        String descricao ="";
        String quantidade ="";
        String preco="";
        
        ArrayList <Jogo> vetJogo = new ArrayList<>();
        try{
            FileInputStream fileinput = new FileInputStream("dadosJogo.txt");
            ObjectInputStream input = new ObjectInputStream(fileinput);
            //guarda o que foi lido no arrayList
            vetJogo = (ArrayList<Jogo>) input.readObject();
            TelaTabelaJogo tabela = new TelaTabelaJogo();
            DefaultTableModel envia = (DefaultTableModel) tabela.getTabelaJogo().getModel(); 
            
            //Jogo j = new Jogo(nome, censura, categoria, desenvolvedora, descricao, quantidade, preco);
            for(int i=0; i<vetJogo.size(); i++){
                Object [] jogo = {
                vetJogo.get(i).getNome(),
                vetJogo.get(i).getDesenvolvedora(),
                vetJogo.get(i).getCategoria(),
                vetJogo.get(i).getCensura(),
                vetJogo.get(i).getDescricao(),
                vetJogo.get(i).getQuantidade(),
                vetJogo.get(i).getPreco(),
                vetJogo.get(i).getTipo()};
                
                envia.addRow(jogo);
            }
            tabela.setVisible(true);
        }
        catch(IOException e1){
        }
        catch(ClassNotFoundException e2){
        }
    
    }//GEN-LAST:event_jMTabelaJogosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaAlternativaP tap = new TelaAlternativaP();
        tap.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        TelaCadastroEmpresa telaCadastroEmpresa = new TelaCadastroEmpresa();
        telaCadastroEmpresa.setVisible(true);    
    }//GEN-LAST:event_jMenuItem31ActionPerformed
    
    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        TelaCaixadePesquisaEmpresa pesquisa = new TelaCaixadePesquisaEmpresa();
        pesquisa.setVisible(true);
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        ExcluirDadosEmpresa exclui = new ExcluirDadosEmpresa();
        exclui.setVisible(true);
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        TelaAtualizarDadosEmpresa att= new TelaAtualizarDadosEmpresa();
        att.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jPesquisaPersonalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisaPersonalizadaActionPerformed
    
        TelaAlternativaPesquisa pesquisa = new TelaAlternativaPesquisa ();
        pesquisa.setVisible(true);
        
            // TODO add your handling code here:
    }//GEN-LAST:event_jPesquisaPersonalizadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAtualizarFunc;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLAdmLogado;
    private javax.swing.JLabel jLDataAtual;
    private javax.swing.JLabel jLHoraAtual;
    private javax.swing.JLabel jLNomeEmpresa;
    private javax.swing.JMenu jMArquivo_tFunc;
    private javax.swing.JMenu jMArquivo_tFunc1;
    private javax.swing.JMenu jMArquivo_tFunc2;
    private javax.swing.JMenu jMArquivo_tFunc3;
    private javax.swing.JMenu jMArquivo_tFunc4;
    private javax.swing.JMenu jMArquivo_tFunc5;
    private javax.swing.JMenuItem jMTabelaJogos;
    private javax.swing.JMenuItem jMenuAbrirRelatorio;
    private javax.swing.JMenuItem jMenuAdicionarCliente;
    private javax.swing.JMenuItem jMenuAdicionarFuncionario;
    private javax.swing.JMenuItem jMenuAttAdm;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExcluirFuncionario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItemProcurarAdm;
    private javax.swing.JMenuItem jMenuProcurarCliene;
    private javax.swing.JMenuItem jMenuProcurarFuncionario;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuSobre;
    private javax.swing.JMenuItem jMenuaddAds;
    private javax.swing.JMenuItem jMenuexcluirAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jPesquisaPersonalizada;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            Calendar now = Calendar.getInstance();
            jLHoraAtual.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }

}
