package TelasSecundariasAdministrador;

import codigo.Administrador;

import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Arrays;

import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.text.MaskFormatter;

public class TelaProcurarAtualizarAdm extends javax.swing.JFrame {

    ArrayList<Administrador> admArray = new ArrayList<>();
    File arq = new File("dadosAdministrador.txt");
    String procura;

    public TelaProcurarAtualizarAdm(String CPF) {
        initComponents();
        this.procura = CPF;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JtFEmailAdmin = new java.awt.TextField();
        JFCPFAdmin = new javax.swing.JFormattedTextField();
        jCBSexoAdmin = new javax.swing.JComboBox<>();
        JFCelularAdmin = new javax.swing.JFormattedTextField();
        JtFNomeAdmin = new java.awt.TextField();
        JFDataNascAdmin = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JtFUserAdmin = new java.awt.TextField();
        jPFSenhaAdmin = new javax.swing.JPasswordField();
        jPFConfirmarSenhaAdmin = new javax.swing.JPasswordField();
        JBSair = new java.awt.Button();
        JBAtualizar = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        JRuaAdmin = new java.awt.TextField();
        JtFBairro = new java.awt.TextField();
        JtFNumero = new java.awt.TextField();
        JtFCidade = new java.awt.TextField();
        JtFNomeCEP = new java.awt.TextField();
        JBSalvar = new java.awt.Button();
        JBRemover = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados Administrador");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS PESSOAIS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CPF");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data de Nascimento");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sexo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("E-mail");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Celular");

        JtFEmailAdmin.setMinimumSize(new java.awt.Dimension(60, 22));

        try {
            JFCPFAdmin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jCBSexoAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino" }));

        try {
            JFCelularAdmin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        JFDataNascAdmin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JFDataNascAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addComponent(JFCPFAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jCBSexoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JtFNomeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JtFEmailAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JFCelularAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(JtFNomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JFCPFAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jCBSexoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFDataNascAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(JtFEmailAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JFCelularAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CADASTRO LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nome de Usuário");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Senha");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Confirmar Senha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JtFUserAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jPFSenhaAdmin)
                    .addComponent(jPFConfirmarSenhaAdmin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JtFUserAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPFSenhaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jPFConfirmarSenhaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        JBSair.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JBSair.setLabel("SAIR");
        JBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSairActionPerformed(evt);
            }
        });

        JBAtualizar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JBAtualizar.setLabel("ATUALIZAR");
        JBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAtualizarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENDEREÇO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Rua");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Número");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("CEP");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Bairro");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Cidade");

        jComboBoxEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Estado", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RO", "RR", "RN", "RS", "SC", "SE", "SP", "TO" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35)
                                .addComponent(JRuaAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JtFBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JtFNomeCEP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JtFNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(64, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(JRuaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(JtFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(JtFNomeCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(JtFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JtFCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        JBSalvar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JBSalvar.setLabel("SALVAR");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBRemover.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        JBRemover.setLabel("REMOVER");
        JBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(JBAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(JBRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(JBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        JBSair.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     *
     * @param evt Ação ao clicar no botão sair
     */
    private void JBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSairActionPerformed
        //se cancelar sai da tela
        this.dispose();
    }//GEN-LAST:event_JBSairActionPerformed

    /**
     *
     * @param CPF recebe o CPF do administrador a ser procurado.
     */
    public void pesquisa(String CPF) {
        int aux = 0;//aux para informar se houve ou não sucesso na busca

        String nome = "";
        String cpf = "";
        String sexo = "";
        String dataNasc = "";
        String email = "";
        String celular = "";
        String CEP = "";

        String cidade = "";
        String bairro = "";
        String rua = "";
        String numero = "";
        String estado = "";

        String username = "";
        String senha = "*****";

        try {
            //lendo arquivo com dados dos administradores
            FileInputStream file = new FileInputStream(arq);
            ObjectInputStream input = new ObjectInputStream(file);

            ArrayList<Administrador> procuraArray = new ArrayList<>();
            procuraArray = (ArrayList) input.readObject();

            for (Administrador a : procuraArray) {
                if (a.getCPF().equals(this.procura)) {
                    nome = a.getNome();
                    cpf = a.getCPF();
                    sexo = a.getSexo();
                    dataNasc = a.getDataNasc();
                    email = a.getEmail();
                    celular = a.getCelular();

                    cidade = a.getCidade();
                    bairro = a.getBairro();
                    rua = a.getRua();
                    numero = a.getNumero();
                    estado = a.getEstado();
                    CEP = a.getCEP();
                    username = a.getUser();
                    senha = "*****";
                    aux = 1;
                }

            }
            if (aux == 1) { //Foi encontrado administrador com sucesso
                this.setVisible(true);
                JtFNomeAdmin.setEnabled(false);
                JFCPFAdmin.setEnabled(false);
                jCBSexoAdmin.setEnabled(false);
                JFDataNascAdmin.setEnabled(false);
                JtFEmailAdmin.setEnabled(false);
                JFCelularAdmin.setEnabled(false);
                JtFCidade.setEnabled(false);
                JtFBairro.setEnabled(false);
                JRuaAdmin.setEnabled(false);
                JtFNumero.setEnabled(false);
                jComboBoxEstado.setEnabled(false);
                JtFUserAdmin.setEnabled(false);
                jPFSenhaAdmin.setEnabled(false);
                jPFConfirmarSenhaAdmin.setEnabled(false);
                JtFNomeCEP.setEnabled(false);

                JtFNomeAdmin.setText(nome);
                JFCPFAdmin.setText(cpf);
                jCBSexoAdmin.setSelectedItem(sexo);
                JFDataNascAdmin.setText(dataNasc);
                JtFEmailAdmin.setText(email);
                JFCelularAdmin.setText(celular);
                JtFCidade.setText(cidade);
                JtFBairro.setText(bairro);
                JRuaAdmin.setText(rua);
                JtFNumero.setText(numero);
                jComboBoxEstado.setSelectedItem(estado);
                JtFUserAdmin.setText(username);
                jPFSenhaAdmin.setText(senha);
                JtFNomeCEP.setText(CEP);
                jPFConfirmarSenhaAdmin.setText(senha);

                //Caso não exista administrador cadastrado como o cpf procurado
            } else if (aux == 0) {
                JOptionPane.showMessageDialog(null, "Não existe cadastro para o Administrador procurado!");
                MaskFormatter formato = null;
                try {
                    formato = new MaskFormatter("###.###.###-##");
                } catch (ParseException ex) {
                }
                JLabel label = new JLabel("Informe o CPF que deseja procurar: ");
                JFormattedTextField texto = new JFormattedTextField(formato);
                //UIManager.put("OptionPane.okButtonText", "Pesquisar");
                JOptionPane.showMessageDialog(null, new Object[]{label, texto});

                String procuraAdmin = texto.getText();

                //TelaProcurarAtualizarAdm tela = new TelaProcurarAtualizarAdm();
                if (!"   .   .   -  ".equals(procuraAdmin)) {
                    pesquisa(procuraAdmin);
                } else {
                    System.out.println("Sair");
                }
            }

            input.close();

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        }

    }

    /**
     * Método para o menu "Atualizar" da barra de Menu da Tela principal
     * Administrador
     */
    public void Atualizar() {

        int aux = 0;//aux para informar se houve ou não sucesso na busca

        String nome = "";
        String cpf = "";
        String sexo = "";
        String dataNasc = "";
        String email = "";
        String celular = "";
        String CEP = "";

        String cidade = "";
        String bairro = "";
        String rua = "";
        String numero = "";
        String estado = "";

        String username = "";
        String senha = "*****";

        try {
            //lendo arquivo com dados dos administradores
            FileInputStream file = new FileInputStream(arq);
            ObjectInputStream input = new ObjectInputStream(file);

            ArrayList<Administrador> procuraArray = new ArrayList<>();
            procuraArray = (ArrayList) input.readObject();

            for (Administrador a : procuraArray) {
                if (a.getCPF().equals(this.procura)) {
                    nome = a.getNome();
                    cpf = a.getCPF();
                    sexo = a.getSexo();
                    dataNasc = a.getDataNasc();
                    email = a.getEmail();
                    celular = a.getCelular();

                    cidade = a.getCidade();
                    bairro = a.getBairro();
                    rua = a.getRua();
                    numero = a.getNumero();
                    estado = a.getEstado();
                    CEP = a.getCEP();
                    username = a.getUser();
                    senha = "*****";
                    aux = 1;
                }

            }
            if (aux == 1) { //Foi encontrado administrador com sucesso
                this.setVisible(true);
                JtFNomeAdmin.setEnabled(false);
                JFCPFAdmin.setEnabled(false);
                jCBSexoAdmin.setEnabled(false);
                JFDataNascAdmin.setEnabled(false);
                JtFEmailAdmin.setEnabled(false);
                JFCelularAdmin.setEnabled(false);
                JtFCidade.setEnabled(false);
                JtFBairro.setEnabled(false);
                JRuaAdmin.setEnabled(false);
                JtFNumero.setEnabled(false);
                jComboBoxEstado.setEnabled(false);
                JtFUserAdmin.setEnabled(false);
                jPFSenhaAdmin.setEnabled(false);
                jPFConfirmarSenhaAdmin.setEnabled(false);
                JtFNomeCEP.setEnabled(false);

                JtFNomeAdmin.setText(nome);
                JFCPFAdmin.setText(cpf);
                jCBSexoAdmin.setSelectedItem(sexo);
                JFDataNascAdmin.setText(dataNasc);
                JtFEmailAdmin.setText(email);
                JFCelularAdmin.setText(celular);
                JtFCidade.setText(cidade);
                JtFBairro.setText(bairro);
                JRuaAdmin.setText(rua);
                JtFNumero.setText(numero);
                jComboBoxEstado.setSelectedItem(estado);
                JtFUserAdmin.setText(username);
                jPFSenhaAdmin.setText(senha);
                JtFNomeCEP.setText(CEP);
                jPFConfirmarSenhaAdmin.setText(senha);

                //Caso não exista administrador cadastrado como o cpf procurado
            } else if (aux == 0) {
                JOptionPane.showMessageDialog(null, "Não existe cadastro para o Administrador procurado!");
                MaskFormatter formato = null;
                try {
                    formato = new MaskFormatter("###.###.###-##");
                } catch (ParseException ex) {
                }
                JLabel label = new JLabel("Informe o CPF que deseja procurar: ");
                JFormattedTextField texto = new JFormattedTextField(formato);
                //UIManager.put("OptionPane.okButtonText", "Pesquisar");
                JOptionPane.showMessageDialog(null, new Object[]{label, texto});

                String procuraAdmin = texto.getText();

                //TelaProcurarAtualizarAdm tela = new TelaProcurarAtualizarAdm();
                if (!"   .   .   -  ".equals(procuraAdmin)) {
                    pesquisa(procuraAdmin);
                } else {
                    System.out.println("Sair");
                }
            }

            input.close();

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        }

        JtFNomeAdmin.setEnabled(true);
        JFCPFAdmin.setEnabled(true);
        jCBSexoAdmin.setSelectedItem(sexo);
        jCBSexoAdmin.setEnabled(true);

        JFDataNascAdmin.setEnabled(true);
        JtFEmailAdmin.setEnabled(true);
        JFCelularAdmin.setEnabled(true);
        JtFCidade.setEnabled(true);
        JtFBairro.setEnabled(true);
        JRuaAdmin.setEnabled(true);
        JtFNumero.setEnabled(true);
        jComboBoxEstado.setSelectedItem(estado);
        jComboBoxEstado.setEnabled(true);
        JtFUserAdmin.setEnabled(true);
        //jPFSenhaAdmin.setEnabled(true);
        //jPFConfirmarSenhaAdmin.setEnabled(true);
        JtFNomeCEP.setEnabled(true);
    }

    /**
     *
     * @param evt ao apertar o botão atualizar os campos se tornam editaveis
     */
    private void JBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAtualizarActionPerformed

        String estado = (String) jComboBoxEstado.getSelectedItem();
        String sexo = (String) jCBSexoAdmin.getSelectedItem();

        JtFNomeAdmin.setEnabled(true);
        JFCPFAdmin.setEnabled(true);
        jCBSexoAdmin.setSelectedItem(sexo);
        jCBSexoAdmin.setEnabled(true);

        JFDataNascAdmin.setEnabled(true);
        JtFEmailAdmin.setEnabled(true);
        JFCelularAdmin.setEnabled(true);
        JtFCidade.setEnabled(true);
        JtFBairro.setEnabled(true);
        JRuaAdmin.setEnabled(true);
        JtFNumero.setEnabled(true);
        jComboBoxEstado.setSelectedItem(estado);
        jComboBoxEstado.setEnabled(true);
        JtFUserAdmin.setEnabled(true);
        //jPFSenhaAdmin.setEnabled(true);
        //jPFConfirmarSenhaAdmin.setEnabled(true);
        JtFNomeCEP.setEnabled(true);

    }//GEN-LAST:event_JBAtualizarActionPerformed

    /**
     *
     * @param evt Evento ao clicar no botão "salvar" após editar cadastro
     */
    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        removerParaAtualizar();

    }//GEN-LAST:event_JBSalvarActionPerformed
    /**
     * Primeiro é feita a remoção do administrador, depois salvo seu cadastro
     * novamente atualizado, para evitar duplicatas no arquivo
     */
    public void removerParaAtualizar() {
        int remover = 0;
        try {
            FileInputStream file = new FileInputStream(arq);
            try (ObjectInputStream input = new ObjectInputStream(file)) {
                ArrayList<Administrador> atualizarArray = new ArrayList<>();
                atualizarArray = (ArrayList<Administrador>) input.readObject();

                for (Administrador a : atualizarArray) {
                    if (a.getCPF().equals(this.procura)) {
                        remover = atualizarArray.indexOf(a);
                    }
                }

                atualizarArray.remove(remover);

                FileOutputStream stream = new FileOutputStream(arq);
                try (ObjectOutputStream output = new ObjectOutputStream(stream)) {
                    output.writeObject(atualizarArray);
                    output.flush();
                    output.close();
                }
            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        }
        /**
         * Coletadand os novos dados inseridos na tela e salva em arquivo.
         */
        int i = 0;
        String nome = JtFNomeAdmin.getText();
        String cpf = JFCPFAdmin.getText();
        String sexo = jCBSexoAdmin.getSelectedItem().toString();
        String dataNasc = JFDataNascAdmin.getText();
        String email = JtFEmailAdmin.getText();
        String celular = JFCelularAdmin.getText();

        String cidade = JtFCidade.getText();
        String bairro = JtFBairro.getText();
        String CEP = JtFNomeCEP.getText();
        String rua = JRuaAdmin.getText();
        String numero = JtFNumero.getText();
        String estado = jComboBoxEstado.getSelectedItem().toString();

        String username = JtFUserAdmin.getText();
        String senha = jPFSenhaAdmin.getText();

        try {
            FileInputStream fileinput = new FileInputStream(arq);
            //SALVO NO ARRAY O ARQUIVO ORIGINAL
            try (ObjectInputStream input = new ObjectInputStream(fileinput)) {
                //SALVO NO ARRAY O ARQUIVO ORIGINAL
                admArray = (ArrayList<Administrador>) input.readObject();
                admArray.add(new Administrador(username, nome, cpf, dataNasc, sexo, rua, numero, bairro, CEP, cidade, estado, celular, email, senha));
                try {
                    FileOutputStream fo = new FileOutputStream(arq);
                    try (ObjectOutputStream escreve = new ObjectOutputStream(fo)) {
                        escreve.writeObject(admArray);
                        escreve.flush();
                    }
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
                }
            }
            this.dispose();
            JOptionPane.showMessageDialog(null, "Cadastro Atualizado com Sucesso");
        } catch (EOFException e) {

        } catch (ClassNotFoundException | IOException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        }

    }

    /**
     *
     * @param evt ação ao clicar no botão de "remover"
     */
    private void JBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRemoverActionPerformed
        // TODO add your handling code here:
        int remover = 0;
        try {
            FileInputStream file = new FileInputStream(arq);
            try (ObjectInputStream input = new ObjectInputStream(file)) {
                ArrayList<Administrador> atualizarArray = new ArrayList<>();
                atualizarArray = (ArrayList<Administrador>) input.readObject();
                System.out.println("ANTES: " + Arrays.toString(atualizarArray.toArray()));
                for (Administrador a : atualizarArray) {
                    if (a.getCPF().equals(this.procura)) {
                        remover = atualizarArray.indexOf(a);
                    }
                }

                atualizarArray.remove(remover);

                System.out.println("DEPOIS: " + Arrays.toString(atualizarArray.toArray()));
                FileOutputStream stream = new FileOutputStream(arq);
                try (ObjectOutputStream output = new ObjectOutputStream(stream)) {
                    output.writeObject(atualizarArray);
                    output.flush();
                    output.close();
                }
            }
            this.dispose();
            JOptionPane.showMessageDialog(null, "Cadastro Excluído com sucesso!");

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "OCorreu um erro durante a manipulação do arquivo de dados");
        }
    }//GEN-LAST:event_JBRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProcurarAtualizarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProcurarAtualizarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProcurarAtualizarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProcurarAtualizarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProcurarAtualizarAdm("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button JBAtualizar;
    private java.awt.Button JBRemover;
    private java.awt.Button JBSair;
    private java.awt.Button JBSalvar;
    private javax.swing.JFormattedTextField JFCPFAdmin;
    private javax.swing.JFormattedTextField JFCelularAdmin;
    private javax.swing.JFormattedTextField JFDataNascAdmin;
    private java.awt.TextField JRuaAdmin;
    private java.awt.TextField JtFBairro;
    private java.awt.TextField JtFCidade;
    private java.awt.TextField JtFEmailAdmin;
    private java.awt.TextField JtFNomeAdmin;
    private java.awt.TextField JtFNomeCEP;
    private java.awt.TextField JtFNumero;
    private java.awt.TextField JtFUserAdmin;
    private javax.swing.JComboBox<String> jCBSexoAdmin;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPFConfirmarSenhaAdmin;
    private javax.swing.JPasswordField jPFSenhaAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
