/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasSecundariasFuncionarios;

import codigo.ValeCompras;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class TelaCadastroValeCompras extends javax.swing.JFrame {

    static private ArrayList<ValeCompras> valeArray = new ArrayList<>();
    File arq = new File("dadosValeCompras.txt");

    /**
     * @return the valeArray
     */
    public static ArrayList<ValeCompras> getValeArray() {
        return valeArray;
    }

    /**
     * Creates new form TelaCadastroValeCompras
     */
    public TelaCadastroValeCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFIdentificacao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableValesComprasExistentes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFTDataVigor = new javax.swing.JFormattedTextField();
        jFTDataValidade = new javax.swing.JFormattedTextField();
        jBInserir = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar vale-compras");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Identificação do vale-compras:");

        jTFIdentificacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Valor:");

        jTFValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTableValesComprasExistentes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableValesComprasExistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vale-Compras", "Valor", "Data vigor", "Data validade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableValesComprasExistentes);
        if (jTableValesComprasExistentes.getColumnModel().getColumnCount() > 0) {
            jTableValesComprasExistentes.getColumnModel().getColumn(0).setMinWidth(250);
            jTableValesComprasExistentes.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTableValesComprasExistentes.getColumnModel().getColumn(1).setMinWidth(100);
            jTableValesComprasExistentes.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableValesComprasExistentes.getColumnModel().getColumn(2).setMinWidth(150);
            jTableValesComprasExistentes.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableValesComprasExistentes.getColumnModel().getColumn(3).setMinWidth(150);
            jTableValesComprasExistentes.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data vigor:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Data validade:");

        jFTDataVigor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFTDataVigor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFTDataValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFTDataValidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jBInserir.setText("INSERIR");
        jBInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInserirActionPerformed(evt);
            }
        });

        jBSair.setText("SAIR");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFTDataVigor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFTDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBInserir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBSair, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFTDataVigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFTDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jBInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInserirActionPerformed
        String identificacao = jTFIdentificacao.getText();
        double valor = 0;

        String dataVigor = jFTDataVigor.getText();
        String dataValidade = jFTDataValidade.getText();
        int cont = 0;

        if (!identificacao.equals("") &&!jTFValor.getText().equals("")&& !dataVigor.equals("") && !dataValidade.equals("")) {
            try {
                valor = Double.parseDouble(jTFValor.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Valor inválido. Por favor, informe um valor válido!");
            }
            //gravar dados em um arquivo
            if (!arq.exists()) {

                try {
                    if (arq.createNewFile()) {
                        System.out.println("O arquivo foi criado");
                    } else {
                        System.out.println("O arquivo não foi criado");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            try {
                FileInputStream fileinput = new FileInputStream(arq);
                ObjectInputStream input = new ObjectInputStream(fileinput);
                //SALVO NO ARRAY O ARQUIVO ORIGINAL
                valeArray = (ArrayList<ValeCompras>) input.readObject();
                input.close();

            } catch (EOFException e) {

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Verificação se existe vale já cadastrado com mesma identificacao
            for (ValeCompras d : getValeArray()) {
                if (d.getIdentificacao().equals(identificacao)) {
                    JOptionPane.showMessageDialog(null, "Vale compras já cadastrado no sistema!");
                    jTFIdentificacao.setText("");
                    cont = 1;
                    break;
                }

            }
            //gravar no arquivo
            if (cont == 0) {
                valeArray.add(new ValeCompras(identificacao, valor + "", dataVigor, dataValidade));

                FileOutputStream fo;
                try {
                    fo = new FileOutputStream(arq);
                    ObjectOutputStream escreve;
                    escreve = new ObjectOutputStream(fo);
                    escreve.writeObject(valeArray);
                    escreve.flush();
                    escreve.close();
                    JOptionPane.showMessageDialog(null, "Vale-compra cadastrado com sucesso!");
                    jTFIdentificacao.setText("");
                    jTFValor.setText("");
                    jFTDataVigor.setText("");
                    jFTDataValidade.setText("");
                    cont=2;
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Ainda a dados a serem inseridos!");
        }

        /**
         * **********************************************Mostrar vale-compras
         * cadastrados na
         * tabela************************************************************
         */
        if(cont==2){
        DefaultTableModel dtmTabelaValeCompras = (DefaultTableModel) jTableValesComprasExistentes.getModel();

        Object[] dados = {identificacao, valor, dataVigor, dataValidade};
        dtmTabelaValeCompras.addRow(dados);
        }


    }//GEN-LAST:event_jBInserirActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

//exibir tabela de vale compras existentes
        DefaultTableModel dtmTabelaValeCompras = (DefaultTableModel) jTableValesComprasExistentes.getModel();

        //ler arquivo
        try {
            FileInputStream fileinput = new FileInputStream(arq);
            ObjectInputStream input = new ObjectInputStream(fileinput);
            //SALVO NO ARRAY O ARQUIVO ORIGINAL
            valeArray = (ArrayList<ValeCompras>) input.readObject();
            input.close();

        } catch (EOFException e) {

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!valeArray.isEmpty()) {
            for (int i = 0; i < getValeArray().size(); i++) {
                Object[] dados = {getValeArray().get(i).getIdentificacao(), getValeArray().get(i).getValor(), getValeArray().get(i).getDataVigor(), getValeArray().get(i).getDataValidade()};
                dtmTabelaValeCompras.addRow(dados);
            }
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroValeCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroValeCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInserir;
    private javax.swing.JButton jBSair;
    private javax.swing.JFormattedTextField jFTDataValidade;
    private javax.swing.JFormattedTextField jFTDataVigor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFIdentificacao;
    private javax.swing.JTextField jTFValor;
    private javax.swing.JTable jTableValesComprasExistentes;
    // End of variables declaration//GEN-END:variables
}
